# Generated by Django 5.0 on 2025-05-20 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("encrypted_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("unlock_after", models.DateTimeField(blank=True, null=True)),
                ("passphrase_hash", models.CharField(blank=True, max_length=255)),
                ("salt", models.CharField(blank=True, max_length=255)),
                ("encrypted_key", models.TextField(blank=True)),
                ("self_destruct", models.BooleanField(default=False)),
                ("has_been_viewed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
