# Generated by Django 5.0 on 2025-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagesvault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagevault",
            name="encrypted_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
